modLoader = "javafml"
loaderVersion = "[0,)"
license = "MIT"
issueTrackerURL = "https://github.com/PTOM76/uncraftingtable/issues"

[[mods]]
modId = "uncraftingtable76"
version = "${version}"
displayName = "Uncrafting Table"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/simple-uncrafting-table-fabric"
logoFile = "icon.png"
authors = "Pitan"
description = '''

'''

[[dependencies.uncraftingtable76]]
modId = "forge"
mandatory = true
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.uncraftingtable76]]
modId = "minecraft"
mandatory = true
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.uncraftingtable76]]
modId = "architectury"
mandatory = true
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.uncraftingtable76]]
modId = "mcpitanlibarch"
mandatory = true
versionRange = "[1.5.5,)"
ordering = "NONE"
side = "BOTH"
