plugins {
    id "architectury-plugin" version "3.4-SNAPSHOT"
    id "dev.architectury.loom" version "1.6-SNAPSHOT" apply false
    id "me.modmuss50.mod-publish-plugin" version "2.2.0" apply false
}

architectury {
    minecraft = rootProject.minecraft_version
}

subprojects {
    apply plugin: "dev.architectury.loom"
//    apply plugin: "com.modrinth.minotaur"
//    apply plugin: "com.matthewprenger.cursegradle"
    apply plugin: "me.modmuss50.mod-publish-plugin"

    loom {
        silentMojangMappingsLicense()
    }

    repositories {
        maven { url "https://maven.shedaniel.me/" }
        maven { url "https://maven.pitan76.net/" }
        maven { url "https://maven.neoforged.net/releases" }
    }

    dependencies {
        minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
        mappings loom.layered() {
            it.mappings("net.fabricmc:yarn:${rootProject.yarn_mappings}:v2")
            it.mappings file("../mappings/yarnpatch.tiny")
        }

        modCompileOnlyApi "me.shedaniel.cloth:cloth-config:${rootProject.cloth_config_api_version}"

        modCompileOnlyApi "net.pitan76:mcpitanlib-common${rootProject.mcpitanlib_version}"
    }

    publishMods {
        if (name == "common") return

        file = remapJar.archiveFile
        version = rootProject.mod_version
        displayName = remapJar.archiveFileName
        changelog = rootProject.changelog + "\nMCPitanLib version: " + mcpitanlib_version.split(":")[1]

        type = STABLE
        modLoaders.add(name)

        var curseforgeToken = providers.environmentVariable("CURSEFORGE_TOKEN")
        var modrinthToken = providers.environmentVariable("MODRINTH_TOKEN")

        if (curseforgeToken.isPresent()) {
            curseforge {
                accessToken = curseforgeToken
                projectId = "523423"

                if (name != "neoforge") {
                    minecraftVersions.addAll(['1.18', '1.18.1', '1.18.2', '1.19', '1.19.1', '1.19.2', '1.20', '1.20.1', '1.20.3'])
                }
                minecraftVersions.add('1.20.4')
                if (name != "forge") {
                    minecraftVersions.addAll(['1.21', '1.21.1', '1.21.2', '1.21.3', '1.21.4', '1.21.5', '1.21.6',
                                              '1.21.7', '1.21.8', '1.21.9', '1.21.10', '1.21.11',
                                              '26.1', '26.1.1', '26.1.2', '26.2'])
                }

                client = true
                server = true

                requires("fabric-api")
                requires("mcpitanlibarch")
            }
        }

        if (modrinthToken.isPresent()) {
            modrinth {
                accessToken = modrinthToken
                projectId = "d0f1a75r"

                if (name != "neoforge") {
                    minecraftVersions.addAll(['1.18', '1.18.1', '1.18.2', '1.19', '1.19.1', '1.19.2', '1.20', '1.20.1', '1.20.3'])
                }
                minecraftVersions.add('1.20.4')
                if (name != "forge") {
                    minecraftVersions.addAll(['1.21', '1.21.1', '1.21.2', '1.21.3', '1.21.4', '1.21.5', '1.21.6',
                                              '1.21.7', '1.21.8', '1.21.9', '1.21.10', '1.21.11',
                                              '26.1', '26.1.1', '26.1.2', '26.2'])
                }

                requires("fabric-api")
                requires("mcpitanlibarch")
            }
        }
    }
}

allprojects {
    apply plugin: "java"
    apply plugin: "architectury-plugin"
    apply plugin: "maven-publish"

    archivesBaseName = rootProject.archives_base_name
    version = rootProject.mod_version
    group = rootProject.maven_group

    repositories {
        // Add repositories to retrieve artifacts from in here.
        // You should only use this when depending on other mods because
        // Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
        // See https://docs.gradle.org/current/userguide/declaring_repositories.html
        // for more information about repositories.
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = "UTF-8"
        // if neoforge is used, use java 17
        if (project.name == "neoforge") {
            options.release = 17
            sourceCompatibility = JavaVersion.VERSION_17
            targetCompatibility = JavaVersion.VERSION_17
        } else {
            options.release = 8
            sourceCompatibility = JavaVersion.VERSION_1_8
            targetCompatibility = JavaVersion.VERSION_1_8
        }
    }

    java {
        withSourcesJar()
    }
}
